// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(didFFI)
import didFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_didresolver_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_didresolver_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDidresolverInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Represents a Decentralized Identifier (DID) in terms of DID Web + Verifiable History (`did:webvh`)
 * that is an enhancement to the `did:web` DID method, providing complementary features, as specified by
 * https://identity.foundation/didwebvh.
 *
 * Also, the legacy DID method `did:tdw` is supported as well.
 */
public protocol DidProtocol: AnyObject, Sendable {
    
    /**
     * Returns the HTTPS URL "transformed" (w.r.t. https://identity.foundation/didwebvh/next/#the-did-to-https-transformation)
     * from the DID supplied via constructor.
     */
    func getHttpsUrl()  -> String
    
    /**
     * The DID method matching the DID supplied via constructor, if supported. Otherwise, `DidMethod::UNKNOWN`
     */
    func getMethod()  -> DidMethod
    
    /**
     * The self-certifying identifier (SCID) for the DID supplied via constructor.
     */
    func getScid()  -> String
    
    /**
     * Returns the HTTPS URL "transformed" (w.r.t. https://identity.foundation/didwebvh/next/#the-did-to-https-transformation)
     * from the DID supplied via constructor.
     *
     * @deprecated as of 2.2.0 replaced by `get_https_url`
     */
    func getUrl() throws  -> String
    
    /**
     * The essential method of `Did` implementing the "Read (Resolve)" DID method operation for either a
     * `did:tdw:0.3` (w.r.t. https://identity.foundation/didwebvh/v0.3/#read-resolve) or a
     * `did:webvh:1.0` DID (w.r.t. https://identity.foundation/didwebvh/v1.0/#read-resolve).
     *
     * In case of error, the available `DidResolveError` object features all the detailed
     * information required to narrow down the root cause.
     *
     * @deprecated as of 2.2.0 replaced by more potent `resolve_all`
     */
    func resolve(didLog: String) throws  -> DidDoc
    
    /**
     * The essential method of `Did` implementing the "Read (Resolve)" DID method operation for either a
     * `did:tdw:0.3` (w.r.t. https://identity.foundation/didwebvh/v0.3/#read-resolve) or a
     * `did:webvh:1.0` DID (w.r.t. https://identity.foundation/didwebvh/v1.0/#read-resolve).
     *
     * In case of error, the available `DidResolveError` object features all the detailed
     * information required to narrow down the root cause.
     *
     * Compared to `resolve` method, it delivers some additional information
     * (the DID processing parameters) used by the `DID Controller`
     * when publishing the current and subsequent `DID log entries`.
     */
    func resolveAll(didLog: String) throws  -> DidDocExtended
    
}
/**
 * Represents a Decentralized Identifier (DID) in terms of DID Web + Verifiable History (`did:webvh`)
 * that is an enhancement to the `did:web` DID method, providing complementary features, as specified by
 * https://identity.foundation/didwebvh.
 *
 * Also, the legacy DID method `did:tdw` is supported as well.
 */
open class Did: DidProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_didresolver_fn_clone_did(self.pointer, $0) }
    }
    /**
     * The single constructor of `Did` expecting a
     * DID method-specific identifier (defined as https://identity.foundation/didwebvh/next/#method-specific-identifier) as either a
     * `did:tdw:0.3` DID (w.r.t. https://identity.foundation/didwebvh/v0.3) or a
     * `did:webvh:1.0` DID (w.r.t. https://identity.foundation/didwebvh/v1.0).
     *
     * The constructor will attempt to *transform* (w.r.t. https://identity.foundation/didwebvh/next/#the-did-to-https-transformation)
     * the supplied DID method identifier into a valid RFC3986-conform HTTPS URL thus enabling retrival
     * of its DID log (via an `HTTP GET`). In case of error, the available `DidResolveError`
     * object features all the detailed information required to narrow down the root cause.
     */
public convenience init(did: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeDidResolveError_lift) {
    uniffi_didresolver_fn_constructor_did_new(
        FfiConverterString.lower(did),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_didresolver_fn_free_did(pointer, $0) }
    }

    

    
    /**
     * Returns the HTTPS URL "transformed" (w.r.t. https://identity.foundation/didwebvh/next/#the-did-to-https-transformation)
     * from the DID supplied via constructor.
     */
open func getHttpsUrl() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_didresolver_fn_method_did_get_https_url(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The DID method matching the DID supplied via constructor, if supported. Otherwise, `DidMethod::UNKNOWN`
     */
open func getMethod() -> DidMethod  {
    return try!  FfiConverterTypeDidMethod_lift(try! rustCall() {
    uniffi_didresolver_fn_method_did_get_method(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The self-certifying identifier (SCID) for the DID supplied via constructor.
     */
open func getScid() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_didresolver_fn_method_did_get_scid(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Returns the HTTPS URL "transformed" (w.r.t. https://identity.foundation/didwebvh/next/#the-did-to-https-transformation)
     * from the DID supplied via constructor.
     *
     * @deprecated as of 2.2.0 replaced by `get_https_url`
     */
open func getUrl()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDidResolveError_lift) {
    uniffi_didresolver_fn_method_did_get_url(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The essential method of `Did` implementing the "Read (Resolve)" DID method operation for either a
     * `did:tdw:0.3` (w.r.t. https://identity.foundation/didwebvh/v0.3/#read-resolve) or a
     * `did:webvh:1.0` DID (w.r.t. https://identity.foundation/didwebvh/v1.0/#read-resolve).
     *
     * In case of error, the available `DidResolveError` object features all the detailed
     * information required to narrow down the root cause.
     *
     * @deprecated as of 2.2.0 replaced by more potent `resolve_all`
     */
open func resolve(didLog: String)throws  -> DidDoc  {
    return try  FfiConverterTypeDidDoc_lift(try rustCallWithError(FfiConverterTypeDidResolveError_lift) {
    uniffi_didresolver_fn_method_did_resolve(self.uniffiClonePointer(),
        FfiConverterString.lower(didLog),$0
    )
})
}
    
    /**
     * The essential method of `Did` implementing the "Read (Resolve)" DID method operation for either a
     * `did:tdw:0.3` (w.r.t. https://identity.foundation/didwebvh/v0.3/#read-resolve) or a
     * `did:webvh:1.0` DID (w.r.t. https://identity.foundation/didwebvh/v1.0/#read-resolve).
     *
     * In case of error, the available `DidResolveError` object features all the detailed
     * information required to narrow down the root cause.
     *
     * Compared to `resolve` method, it delivers some additional information
     * (the DID processing parameters) used by the `DID Controller`
     * when publishing the current and subsequent `DID log entries`.
     */
open func resolveAll(didLog: String)throws  -> DidDocExtended  {
    return try  FfiConverterTypeDidDocExtended_lift(try rustCallWithError(FfiConverterTypeDidResolveError_lift) {
    uniffi_didresolver_fn_method_did_resolve_all(self.uniffiClonePointer(),
        FfiConverterString.lower(didLog),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDid: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Did

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Did {
        return Did(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Did) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Did {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Did, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDid_lift(_ pointer: UnsafeMutableRawPointer) throws -> Did {
    return try FfiConverterTypeDid.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDid_lower(_ value: Did) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDid.lower(value)
}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum DidMethod {
    
    case tdw(scid: String, httpsUrl: String
    )
    case webvh(scid: String, httpsUrl: String
    )
    case unknown
}


#if compiler(>=6)
extension DidMethod: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDidMethod: FfiConverterRustBuffer {
    typealias SwiftType = DidMethod

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DidMethod {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .tdw(scid: try FfiConverterString.read(from: &buf), httpsUrl: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .webvh(scid: try FfiConverterString.read(from: &buf), httpsUrl: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DidMethod, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .tdw(scid,httpsUrl):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(scid, into: &buf)
            FfiConverterString.write(httpsUrl, into: &buf)
            
        
        case let .webvh(scid,httpsUrl):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(scid, into: &buf)
            FfiConverterString.write(httpsUrl, into: &buf)
            
        
        case .unknown:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDidMethod_lift(_ buf: RustBuffer) throws -> DidMethod {
    return try FfiConverterTypeDidMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDidMethod_lower(_ value: DidMethod) -> RustBuffer {
    return FfiConverterTypeDidMethod.lower(value)
}


extension DidMethod: Equatable, Hashable {}







/**
 * The error accompanying `Did`.
 * It might occur while calling some of the `Did` constructors/methods.
 */
public enum DidResolveError: Swift.Error {

    
    
    /**
     * The supplied DID is not supported. Currently supported are: did:tdw, did:webvh
     */
    case DidNotSupported(message: String)
    
    /**
     * The supplied DID is supported, but is malformed
     */
    case MalformedDid(message: String)
    
    /**
     * The supplied DID log is invalid
     */
    case InvalidDidLog(message: String)
    
    /**
     * The supplied DID log is valid, but it features invalid DID Doc. Alias for `InvalidDidDocument`
     */
    case InvalidDidDoc(message: String)
    
    /**
     * Invalid method-specific identifier
     */
    case InvalidMethodSpecificId(message: String)
    
    /**
     * Failed to serialize DID document (to JSON)
     */
    case SerializationFailed(message: String)
    
    /**
     * The supplied DID document is invalid or contains an argument which isn't part of the did specification/recommendation
     */
    case DeserializationFailed(message: String)
    
    /**
     * Invalid DID method parameter
     */
    case InvalidDidParameter(message: String)
    
    /**
     * The supplied DID log is valid, but it features invalid DID document. Alias for `InvalidDidDoc`
     */
    case InvalidDidDocument(message: String)
    
    /**
     * Invalid DID log integration proof
     */
    case InvalidDataIntegrityProof(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDidResolveError: FfiConverterRustBuffer {
    typealias SwiftType = DidResolveError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DidResolveError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .DidNotSupported(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .MalformedDid(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .InvalidDidLog(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidDidDoc(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .InvalidMethodSpecificId(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .SerializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .DeserializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .InvalidDidParameter(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .InvalidDidDocument(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .InvalidDataIntegrityProof(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DidResolveError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .DidNotSupported(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .MalformedDid(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .InvalidDidLog(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidDidDoc(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .InvalidMethodSpecificId(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .SerializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .DeserializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .InvalidDidParameter(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .InvalidDidDocument(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .InvalidDataIntegrityProof(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDidResolveError_lift(_ buf: RustBuffer) throws -> DidResolveError {
    return try FfiConverterTypeDidResolveError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDidResolveError_lower(_ value: DidResolveError) -> RustBuffer {
    return FfiConverterTypeDidResolveError.lower(value)
}


extension DidResolveError: Equatable, Hashable {}




extension DidResolveError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_didresolver_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_didresolver_checksum_method_did_get_https_url() != 30633) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_method_did_get_method() != 11228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_method_did_get_scid() != 60645) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_method_did_get_url() != 12137) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_method_did_resolve() != 7445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_method_did_resolve_all() != 4445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_didresolver_checksum_constructor_did_new() != 33055) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiEnsureDidSidekicksInitialized()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDidresolverInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all